apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: FolderIAMMember
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/folderiammember
  labels:
    testing.upbound.io/example-name: admin
  name: admin
spec:
  forProvider:
    folderIdSelector:
      matchLabels:
        testing.upbound.io/example-name: yandex_resourcemanager
    role: editor
    serviceAccountSelector:
      matchLabels:
        testing.upbound.io/example-name: example
