apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: FolderIAMBinding
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/folderiambinding
  labels:
    testing.upbound.io/example-name: admin
  name: admin
spec:
  forProvider:
    folderIdSelector:
      matchLabels:
        testing.upbound.io/example-name: yandex_resourcemanager_folder
    role: editor
    serviceAccountsRef:
    - name: example
