apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: ServiceAccountKey
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/serviceaccountkey
  labels:
    testing.upbound.io/example-name: sa-auth-key
  name: sa-auth-key
spec:
  forProvider:
    description: key for service account
    keyAlgorithm: RSA_4096
    pgpKey: keybase:keybaseusername
    serviceAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
