apiVersion: vpc.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Address
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/address
  labels:
    testing.upbound.io/example-name: addr
  name: addr-${data.randomId}
spec:
  forProvider:
    externalIpv4Address:
    - zoneId: ru-central1-a
    name: exampleAddress
  providerConfigRef:
    name: default
