apiVersion: vpc.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Network
metadata:
  name: example-vpc
spec:
  deletionPolicy: Orphan
  forProvider:
    folderIdRef: # you can also use folderId: <your-folder-id> here
      name: example-folder
    name: example-vpc
  providerConfigRef:
    name: example
