apiVersion: vpc.yandex-cloud.jet.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  name: example-security-group
spec:
  forProvider:
    egress:
      - description: rule-egress-all
        fromPort: 0
        protocol: any
        toPort: 65535
        v4CidrBlocks:
          - 0.0.0.0/0
    folderIdRef: # you can also use folderId: <your-folder-id> here
      name: example-folder
    ingress:
      - description: rule-https
        port: 443
        protocol: tcp
        v4CidrBlocks:
          - 0.0.0.0/0
      - description: rule-internal-traffic
        fromPort: 0
        predefinedTarget: self_security_group
        protocol: any
        toPort: 65535
      - description: rule-internal-k8s-pods-services
        fromPort: 0
        protocol: any
        toPort: 65535
        v4CidrBlocks:
          - 10.97.0.0/16
          - 10.113.0.0/16
      - description: rule-yc-balancing
        fromPort: 0
        protocol: tcp
        toPort: 65535
        v4CidrBlocks:
          - 198.18.235.0/24
          - 198.18.248.0/24
      - description: rule-icmp-internal
        protocol: icmp
        v4CidrBlocks:
          - 10.0.0.0/8
          - 192.168.0.0/16
          - 172.16.0.0/12
    name: new
    networkIdRef:
      name: example-vpc # you can also use networkId: <your-network-id> here
  providerConfigRef:
    name: example
