---
apiVersion: vpc.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Subnet
metadata:
  name: example-vpc-ru-central1-a
spec:
  forProvider:
    folderIdRef: # you can also use folderId: <your-folder-id> here
      name: example-folder
    networkIdRef:
      name: example-vpc # you can also use networkId: <your-network-id> here
    v4CidrBlocks:
      - 10.128.0.0/24
    zone: "ru-central1-a"
    name: "example-vpc-ru-central1-a"
  providerConfigRef:
    name: example
---
apiVersion: vpc.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Subnet
metadata:
  name: example-vpc-ru-central1-b
spec:
  forProvider:
    folderIdRef: # you can also use folderId: <your-folder-id> here
      name: example-folder
    networkIdRef:
      name: example-vpc # you can also use networkId: <your-network-id> here
    v4CidrBlocks:
      - 10.129.0.0/24
    zone: "ru-central1-b"
    name: "example-vpc-ru-central1-b"
  providerConfigRef:
    name: example
---
apiVersion: vpc.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Subnet
metadata:
  name: example-vpc-ru-central1-c
spec:
  forProvider:
    folderIdRef: # you can also use folderId: <your-folder-id> here
      name: example-folder
    networkIdRef:
      name: example-vpc # you can also use networkId: <your-network-id> here
    v4CidrBlocks:
      - 10.130.0.0/24
    zone: "ru-central1-c"
    name: "example-vpc-ru-central1-c"
  providerConfigRef:
    name: example
