apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: CloudIAMBinding
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/cloudiambinding
  labels:
    testing.upbound.io/example-name: admin
  name: admin
spec:
  forProvider:
    cloudId: ${data.cloudId}
    role: editor
    serviceAccountRef:
    - name: example-sa
