apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: FolderIAMBinding
metadata:
  name: example-iam-binding
spec:
  deletionPolicy: Orphan
  forProvider:
    folderIdRef:
      name: example-folder # you can also use folderId: <your-folder-id> here
    role: admin
    members: ["serviceAccount:<sa-id>"]
  providerConfigRef:
    name: example
