apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: FolderIAMMember
metadata:
  name: example-iam-member
spec:
  forProvider:
    folderIdRef:
      name: example-folder # you can also use folderId: <your-folder-id> here
    role: storage.editor
    member: "serviceAccount:<sa-id>"
  providerConfigRef:
    name: example