apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: OrganizationIAMBinding
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/organizationiambinding
    upjet.upbound.io/manual-intervention: "ObserveOnly doesn't behave well in tests."
  labels:
    testing.upbound.io/example-name: editor
  name: editor
spec:
  forProvider:
    organizationId: some_organization_id
    role: editor
    serviceAccountRef:
    - name: example-sa
