apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  name: example-sa
spec:
  forProvider:
    folderIdRef:
      name: example-folder # you can also use folderId: <your-folder-id> here
    name: example-sa
  providerConfigRef:
    name: example
