apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: ServiceAccountAPIKey
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/serviceaccountapikey
  labels:
    testing.upbound.io/example-name: sa-api-key
  name: sa-api-key
spec:
  forProvider:
    description: api key for authorization
    serviceAccountIdRef:
      name: example-sa
