apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: ServiceAccountIAMMember
metadata:
  name: example-sa-iam-member
spec:
  forProvider:
    role: "editor"
    serviceAccountId: <sa-id>
    member: "serviceAccount:<sa-id>"
  providerConfigRef:
    name: example
