apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: ServiceAccountStaticAccessKey
metadata:
  name: example-sa-static-key
  labels:
    testing.upbound.io/example-name: storage
  annotations:
    uptest.upbound.io/pre-delete-hook: testhooks/delete-storage.sh
spec:
  forProvider:
    description: "static access key for object storage"
    serviceAccountIdRef:
      name: example-sa
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: sa-key-conn
    namespace: crossplane-system