/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by terrajet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ServiceAccountIamBindingObservation struct {
}

type ServiceAccountIamBindingParameters struct {

	// +kubebuilder:validation:Required
	Members []*string `json:"members" tf:"members,omitempty"`

	// +kubebuilder:validation:Required
	Role *string `json:"role" tf:"role,omitempty"`

	// +kubebuilder:validation:Required
	ServiceAccountID *string `json:"serviceAccountId" tf:"service_account_id,omitempty"`

	// +kubebuilder:validation:Optional
	SleepAfter *int64 `json:"sleepAfter,omitempty" tf:"sleep_after,omitempty"`
}

// ServiceAccountIamBindingSpec defines the desired state of ServiceAccountIamBinding
type ServiceAccountIamBindingSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ServiceAccountIamBindingParameters `json:"forProvider"`
}

// ServiceAccountIamBindingStatus defines the observed state of ServiceAccountIamBinding.
type ServiceAccountIamBindingStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ServiceAccountIamBindingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// ServiceAccountIamBinding is the Schema for the ServiceAccountIamBindings API
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,yandex-cloudjet}
type ServiceAccountIamBinding struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ServiceAccountIamBindingSpec   `json:"spec"`
	Status            ServiceAccountIamBindingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServiceAccountIamBindingList contains a list of ServiceAccountIamBindings
type ServiceAccountIamBindingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServiceAccountIamBinding `json:"items"`
}

// Repository type metadata.
var (
	ServiceAccountIamBinding_Kind             = "ServiceAccountIamBinding"
	ServiceAccountIamBinding_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ServiceAccountIamBinding_Kind}.String()
	ServiceAccountIamBinding_KindAPIVersion   = ServiceAccountIamBinding_Kind + "." + CRDGroupVersion.String()
	ServiceAccountIamBinding_GroupVersionKind = CRDGroupVersion.WithKind(ServiceAccountIamBinding_Kind)
)

func init() {
	SchemeBuilder.Register(&ServiceAccountIamBinding{}, &ServiceAccountIamBindingList{})
}
