apiVersion: v1
kind: Secret
metadata:
  name: kafka-connector
  namespace: default
type: Opaque
data:
  password: MTIzNDU2Nzg=
---
apiVersion: mdb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: KafkaCluster
metadata:
  name: kafka-conn-cluster
spec:
  forProvider:
    config:
      - kafka:
          - resources:
              - diskSize: 16
                diskTypeId: network-hdd
                resourcePresetId: s2.micro
        version: "2.8"
        zones:
          - ru-central1-a
    name: kafka-conn-cluster
    networkIdRef:
      name: example-net
    subnetIdsRefs:
      - name: example-subnet-a
---
apiVersion: mdb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: KafkaConnector
metadata:
  name: connector
spec:
  forProvider:
    clusterIdRef:
      name: kafka-conn-cluster
    connectorConfigMirrormaker:
      - replicationFactor: 1
        sourceCluster:
          - alias: source
            externalCluster:
              - bootstrapServers: somebroker1:9091,somebroker2:9091
                saslMechanism: SCRAM-SHA-512
                saslPasswordSecretRef:
                  key: password
                  name: kafka-connector
                  namespace: default
                saslUsername: someuser
                securityProtocol: SASL_SSL
        targetCluster:
          - alias: target
            thisCluster:
              - {}
        topics: .*
    name: connector
    properties:
      refresh.topics.enabled: "true"
    tasksMax: 3