apiVersion: yandex-cloud.jet.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: token-secret-auth
  annotations:
    upjet.upbound.io/manual-intervention: "Example configuration using token from secret."
spec:
  credentials:
    cloudId: ${data.cloudId}
    folderId: ${data.folderId}
    source: Secret
    secretRef:
      name: example-token-creds
      namespace: crossplane-system
      key: token