# Example ProviderConfig using separate secrets for different credentials
# This demonstrates the new feature that allows storing credentials in separate secrets
apiVersion: yandex-cloud.jet.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: separate-secrets-auth
  annotations:
    upjet.upbound.io/manual-intervention: "Example configuration using separate secrets for service account key and storage credentials."
spec:
  credentials:
    cloudId: ${data.cloudId}
    folderId: ${data.folderId}
    source: Secret
    # Service account key stored in a separate secret
    serviceAccountKeySecretRef:
      name: yc-service-account-key
      namespace: crossplane-system
      key: sa-key.json
    # Storage access key stored in a separate secret
    storageAccessKeySecretRef:
      name: yc-storage-access-key
      namespace: crossplane-system
      key: access-key
    # Storage secret key stored in a separate secret
    storageSecretKeySecretRef:
      name: yc-storage-secret-key
      namespace: crossplane-system
      key: secret-key