apiVersion: ydb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: DatabaseDedicated
metadata:
  annotations:
    meta.upbound.io/example-id: ydb/v1alpha1/databasededicated
  labels:
    testing.upbound.io/example-name: database1
  name: database1
spec:
  forProvider:
    folderIdSelector:
      matchLabels:
        testing.upbound.io/example-name: yandex_resourcemanager_folder
    location:
    - region:
      - id: ru-central1
    name: test-ydb-dedicated
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: my-inst-group-network
    resourcePresetId: medium
    scalePolicy:
    - fixedScale:
      - size: 1
    storageConfig:
    - groupCount: 1
      storageTypeId: ssd
    subnetIdsRefs:
    - name: my-inst-group-subnet
