apiVersion: alb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: LoadBalancer
metadata:
  annotations:
    meta.upbound.io/example-id: alb/v1alpha1/loadbalancer
  labels:
    testing.upbound.io/example-name: test-balancer
  name: test-balancer
spec:
  forProvider:
    allocationPolicy:
    - location:
      - subnetIdSelector:
          matchLabels:
            testing.upbound.io/example-name: test-subnet
        zoneId: ru-central1-a
    listener:
    - endpoint:
      - address:
        - externalIpv4Address:
          - {}
        ports:
        - 8080
      http:
      - handler:
        - httpRouterId: ${yandex_alb_http_router.test-router.id}
      name: my-listener
    name: my-load-balancer
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test-network
