apiVersion: compute.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: example-instance
spec:
  forProvider:
    name: example-instance
    platformId: standard-v1
    zone: ru-central1-a
    resources:
      - cores: 2
        memory: 4
    bootDisk:
      - initializeParams:
          # ubuntu 22.04
          # yc compute image list --folder-id standard-images | grep 'ubuntu-22-04-lts'
          - imageId: fd80bm0rh4rkepi5ksdi
    networkInterface:
      - subnetIdRef:
          name: example-subnet-a
    metadata:
      ssh-keys: "ubuntu:<public-key-data>"
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: instance-conn
    namespace: default