apiVersion: container.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Registry
metadata:
  annotations:
    meta.upbound.io/example-id: container/v1alpha1/registry
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    folderIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    labels:
      my-label: my-label-value
    name: test-registry

---

