apiVersion: container.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Registry
metadata:
  name: example-registry
spec:
  forProvider:
    folderIdRef: # you can also use folderId: <your-folder-id> here
      name: example-folder
    name: example-registry
  providerConfigRef:
    name: example