apiVersion: lb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: NetworkLoadBalancer
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/networkloadbalancer
  labels:
    testing.upbound.io/example-name: example-nlb
  name: example-nlb
spec:
  forProvider:
    attachedTargetGroup:
      - healthcheck:
          - httpOptions:
              - path: /ping
                port: 8080
            name: http
        targetGroupIdRef:
          name: example-tg
    listener:
      - externalAddressSpec:
          - ipVersion: ipv4
        name: my-listener
        port: 8080
    name: example-nlb
