apiVersion: lb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: TargetGroup
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/targetgroup
  labels:
    testing.upbound.io/example-name: example-tg
  name: example-tg
spec:
  forProvider:
    name: example-tg
    regionId: ru-central1
    target:
    - addressRef:
        name: example-instance
      subnetIdRef:
        name: example-subnet-a
