apiVersion: kms.yandex-cloud.jet.crossplane.io/v1alpha1
kind: SymmetricKey
metadata:
  name: example-sk
spec:
  forProvider:
    name: example-sk
    description: provider-jet-yc created KMS key
    defaultAlgorithm: AES_128
    rotationPeriod: 8760h
    folderIdRef:
      name: example-folder
  providerConfigRef:
    name: example