apiVersion: alb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: LoadBalancer
metadata:
  annotations:
    meta.upbound.io/example-id: alb/v1alpha1/loadbalancer
  labels:
    testing.upbound.io/example-name: test-balancer
  name: test-balancer
spec:
  forProvider:
    allocationPolicy:
    - location:
      - subnetIdRef:
          name: example-subnet-a
        zoneId: ru-central1-a
    listener:
    - endpoint:
      - address:
        - externalIpv4Address:
          - {}
        ports:
        - 8080
      http:
      - handler:
        - httpRouterIdRef:
            name: test-router
      name: my-listener
    name: my-load-balancer-${data.randomId}
    networkIdRef:
      name: example-net
  providerConfigRef:
    name: default
