apiVersion: dns.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Zone
metadata:
  name: example-zone
spec:
  deletionPolicy: Orphan
  forProvider:
    folderIdRef:
      name: example-folder # you can also use folderId: <your-folder-id> here
    name: example-zone
    zone: "example.com."
    public: true
  providerConfigRef:
    name: example