// +build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretCiphertext) DeepCopyInto(out *SecretCiphertext) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretCiphertext.
func (in *SecretCiphertext) DeepCopy() *SecretCiphertext {
	if in == nil {
		return nil
	}
	out := new(SecretCiphertext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretCiphertext) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretCiphertextList) DeepCopyInto(out *SecretCiphertextList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecretCiphertext, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretCiphertextList.
func (in *SecretCiphertextList) DeepCopy() *SecretCiphertextList {
	if in == nil {
		return nil
	}
	out := new(SecretCiphertextList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretCiphertextList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretCiphertextObservation) DeepCopyInto(out *SecretCiphertextObservation) {
	*out = *in
	if in.Ciphertext != nil {
		in, out := &in.Ciphertext, &out.Ciphertext
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretCiphertextObservation.
func (in *SecretCiphertextObservation) DeepCopy() *SecretCiphertextObservation {
	if in == nil {
		return nil
	}
	out := new(SecretCiphertextObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretCiphertextParameters) DeepCopyInto(out *SecretCiphertextParameters) {
	*out = *in
	if in.AadContext != nil {
		in, out := &in.AadContext, &out.AadContext
		*out = new(string)
		**out = **in
	}
	if in.KeyID != nil {
		in, out := &in.KeyID, &out.KeyID
		*out = new(string)
		**out = **in
	}
	out.PlaintextSecretRef = in.PlaintextSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretCiphertextParameters.
func (in *SecretCiphertextParameters) DeepCopy() *SecretCiphertextParameters {
	if in == nil {
		return nil
	}
	out := new(SecretCiphertextParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretCiphertextSpec) DeepCopyInto(out *SecretCiphertextSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretCiphertextSpec.
func (in *SecretCiphertextSpec) DeepCopy() *SecretCiphertextSpec {
	if in == nil {
		return nil
	}
	out := new(SecretCiphertextSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretCiphertextStatus) DeepCopyInto(out *SecretCiphertextStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretCiphertextStatus.
func (in *SecretCiphertextStatus) DeepCopy() *SecretCiphertextStatus {
	if in == nil {
		return nil
	}
	out := new(SecretCiphertextStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SymmetricKey) DeepCopyInto(out *SymmetricKey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SymmetricKey.
func (in *SymmetricKey) DeepCopy() *SymmetricKey {
	if in == nil {
		return nil
	}
	out := new(SymmetricKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SymmetricKey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SymmetricKeyIamBinding) DeepCopyInto(out *SymmetricKeyIamBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SymmetricKeyIamBinding.
func (in *SymmetricKeyIamBinding) DeepCopy() *SymmetricKeyIamBinding {
	if in == nil {
		return nil
	}
	out := new(SymmetricKeyIamBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SymmetricKeyIamBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SymmetricKeyIamBindingList) DeepCopyInto(out *SymmetricKeyIamBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SymmetricKeyIamBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SymmetricKeyIamBindingList.
func (in *SymmetricKeyIamBindingList) DeepCopy() *SymmetricKeyIamBindingList {
	if in == nil {
		return nil
	}
	out := new(SymmetricKeyIamBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SymmetricKeyIamBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SymmetricKeyIamBindingObservation) DeepCopyInto(out *SymmetricKeyIamBindingObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SymmetricKeyIamBindingObservation.
func (in *SymmetricKeyIamBindingObservation) DeepCopy() *SymmetricKeyIamBindingObservation {
	if in == nil {
		return nil
	}
	out := new(SymmetricKeyIamBindingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SymmetricKeyIamBindingParameters) DeepCopyInto(out *SymmetricKeyIamBindingParameters) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
	if in.SleepAfter != nil {
		in, out := &in.SleepAfter, &out.SleepAfter
		*out = new(int64)
		**out = **in
	}
	if in.SymmetricKeyID != nil {
		in, out := &in.SymmetricKeyID, &out.SymmetricKeyID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SymmetricKeyIamBindingParameters.
func (in *SymmetricKeyIamBindingParameters) DeepCopy() *SymmetricKeyIamBindingParameters {
	if in == nil {
		return nil
	}
	out := new(SymmetricKeyIamBindingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SymmetricKeyIamBindingSpec) DeepCopyInto(out *SymmetricKeyIamBindingSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SymmetricKeyIamBindingSpec.
func (in *SymmetricKeyIamBindingSpec) DeepCopy() *SymmetricKeyIamBindingSpec {
	if in == nil {
		return nil
	}
	out := new(SymmetricKeyIamBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SymmetricKeyIamBindingStatus) DeepCopyInto(out *SymmetricKeyIamBindingStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SymmetricKeyIamBindingStatus.
func (in *SymmetricKeyIamBindingStatus) DeepCopy() *SymmetricKeyIamBindingStatus {
	if in == nil {
		return nil
	}
	out := new(SymmetricKeyIamBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SymmetricKeyList) DeepCopyInto(out *SymmetricKeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SymmetricKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SymmetricKeyList.
func (in *SymmetricKeyList) DeepCopy() *SymmetricKeyList {
	if in == nil {
		return nil
	}
	out := new(SymmetricKeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SymmetricKeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SymmetricKeyObservation) DeepCopyInto(out *SymmetricKeyObservation) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = new(string)
		**out = **in
	}
	if in.RotatedAt != nil {
		in, out := &in.RotatedAt, &out.RotatedAt
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SymmetricKeyObservation.
func (in *SymmetricKeyObservation) DeepCopy() *SymmetricKeyObservation {
	if in == nil {
		return nil
	}
	out := new(SymmetricKeyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SymmetricKeyParameters) DeepCopyInto(out *SymmetricKeyParameters) {
	*out = *in
	if in.DefaultAlgorithm != nil {
		in, out := &in.DefaultAlgorithm, &out.DefaultAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.FolderID != nil {
		in, out := &in.FolderID, &out.FolderID
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.RotationPeriod != nil {
		in, out := &in.RotationPeriod, &out.RotationPeriod
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SymmetricKeyParameters.
func (in *SymmetricKeyParameters) DeepCopy() *SymmetricKeyParameters {
	if in == nil {
		return nil
	}
	out := new(SymmetricKeyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SymmetricKeySpec) DeepCopyInto(out *SymmetricKeySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SymmetricKeySpec.
func (in *SymmetricKeySpec) DeepCopy() *SymmetricKeySpec {
	if in == nil {
		return nil
	}
	out := new(SymmetricKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SymmetricKeyStatus) DeepCopyInto(out *SymmetricKeyStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SymmetricKeyStatus.
func (in *SymmetricKeyStatus) DeepCopy() *SymmetricKeyStatus {
	if in == nil {
		return nil
	}
	out := new(SymmetricKeyStatus)
	in.DeepCopyInto(out)
	return out
}
